name: Build for Windows

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  program_name: game2anki

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Set up NASM
        uses: ilammy/setup-nasm@v1

      - name: Build for target
        shell: bash
        run: |
          program_name=${{ env.program_name }}
          target=x86_64-pc-windows-msvc

          echo "构建目标: $target"
          rustup target add $target
          cargo build --release --target=$target

      - name: Check dependencies (optional)
        shell: powershell
        run: |
          $program_name = "${{ env.program_name }}"
          $target = "x86_64-pc-windows-msvc"
          $exe_path = "target\$target\release\$program_name.exe"

          Write-Host "检查可执行文件依赖:"
          if (Get-Command "dumpbin.exe" -ErrorAction SilentlyContinue) {
            & "dumpbin.exe" /dependents $exe_path
          } else {
            Write-Host "dumpbin不可用，跳过依赖检查"
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.program_name }}_windows_x64
          path: target/x86_64-pc-windows-msvc/release/${{ env.program_name }}.exe
